Define user_ns in IPython.embed() to avoid scope issues.
Using embed() causes scope problems when defining functions in the environment. By default, any modules imported in the ipython embedded shell aren't available to functions defined later in the shell.

This avoids problems like:
In [1]: from geometry_msgs.msg import Pose2D
In [2]: def pose():
   ...:     return Pose2D()
In [3]: pose()
NameError: global name 'Pose2D' is not defined

From docs:
IPython.embed() puts a shell in a particular calling scope, such as a function or method for debugging purposes, which is often not desirable.